import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { XPProvider, useXP } from "./context/XPContext";
import LevelUpModal from "@/components/LevelUpModal";
import AchievementModal from "@/components/AchievementModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function AchievementWatcher() {
  const { activeAchievement, setActiveAchievement } = useXP();
  return (
    <AchievementModal
      open={!!activeAchievement}
      achievement={activeAchievement}
      onClose={() => setActiveAchievement(null)}
    />
  );
}
